import React from "react";
import "./App.css";

import { Routes, Route, Link } from "react-router-dom";

import Header from "./components/header/Header";
import Info from "./components/info/Info";
import Footer from "./components/footer/Footer";
import AddWords from "./components/addWords/AddWords";
import FooterMain from "./components/footer/FooterMain";
import CreatedWords from "./components/checkWords/CheckWords";
import FooterCheck from "./components/footer/FooterCheck";
import Game from "./components/game/Game";
import FooterGame from "./components/footer/FooterGame";
import Layout from "./components/layout/Layout";

import InfoPage from "./page/InfoPage";
import MainPages from "./page/MainPages";
import CheckPage from "./page/CheckPage";
import GamePage from "./page/GamePage";
import NotfoundPage from "./page/NotfoundPage";

const col_1 = [
  "поддерживать ",
  "озеро ",
  "река",
  "совет",
  "известный",
  "стол ",
  "письменый стол",
  "садиться ",
  "подыматься",
  "быстро ",
  "сбежать ",
  "сломать",
  "мост ",
  "сначала ",
  "серьезно ",
  "приносить ",
  "настоящий",
  "счастья",
  "достачно",
  "правильно",
  "решать",
  "сдал прошел",
  "екзамен",
  "экскурсия ",
  "поездка",
  "домашние задание",
  "праздновать ",
  "праздник",
  "совершенно ",
  "грустный",
  "мне, меня",
  "ты",
  "его, ему",
  "ей, ее",
  "оно ",
  "нам, нас",
  "наш",
  "ваш, твой ",
  "им",
  "их",
  "это",
  "эти",
  "тот",
  "те",
  "уставший",
  "болен",
  "злой",
  "необычно",
  "удивлен",
  "шутка",
  "скачать ",
  "эффективный",
  "минута ",
  "мускулы",
  "пол часа",
  "одежда",
  "вирус",
  "иметь значения ",
  "вдохновлять ",
  "существовать ",
  "такая , такие",
  "теория",
  "может ",
  "все",
  "не все",
  "зависетть ",
  "метод ",
  "тоже ",
  "мнения ",
  "такой же ",
  "человек",
  "звук",
  "привлекательный",
  "мир",
  "довольно ",
  "обожать английский",
  "потому что ",
  "большой ",
  "носитель языка",
  "замечательное, прекрасное ",
  "вдохновения",
  "правда",
  "четко, ясно ",
  "задача",
  "отличный ",
  "блестящий ",
  "здание",
  "высокий",
  "низкий ",
  "чуство",
  "вкусный",
  "в наше время",
  "дети ",
  "ребенок",
  "дети ",
  "ребенок",
  "погода ",
  "умный",
  "умный",
  "талантливый",
  "смотреть ",
  "выглядеть ",
  "сильный ",
  "в одно и тот же",
  "родители",
  "двоюродный брат/сестра",
  "вырожения ",
  "еффектный",
  "холодно ",
  "тепло ",
  "жарко ",
  "солнечно ",
  "ветренно ",
  "ветер",
  "необходимое ",
  "деталь ",
  "подробный ",
  "информативный ",
  "описание ",
  "описывать ",
  "удивляет ",
  "мотивация ",
  "мотивирует ",
  "мотивировать ",
  "простой",
  "менеджер по продажам ",
  "продавец",
  "юрист ",
  "закон ",
  "рекомендует ",
  "сувенир ",
  "переводить ",
  "беспокоиться ",
  "иностранный ",
  "язык",
  "что касается меня ",
  "ожидать ",
  "однажды",
  "рано или поздно ",
  "предпологать ",
  "накопить ",
  "надежда",
  "бояться ",
  "неправильно поймет ",
  "надежный ",
  "еще раз",
  "экран",
  "время от времени ",
  "иностранец",
  "на выставке",
  "почти ",
  "консультант",
  "презвонить мне ",
  "достигать ",
  "пара",
  "что нибудь ",
  "мудрый ",
  "тренировка ",
  "темный",
  "поворот ",
  "обьяснения ",
  "неожиданно ",
  "следовать , следить ",
  "рекомендации",
  "обьяснять ",
  "тратить впустую",
  "создавать ",
  "трудности ",
  "затем, чем ",
  "помнить ",
  "чуть-чуть",
  "умереть ",
  "доход",
  "убийство , убить ",
  "успешный ",
  "успешно ",
  "успех",
  "способность ",
  "развиваться, развивать ",
  "благодарить ",
  "товар , товары ",
  "производить ",
  "фабрика",
  "продукция",
  "беда",
  "в беде",
  "всегда",
  "присоеденяться ",
  "закрывать ",
  "делиться ",
  "сылка",
  "сохранять",
  "готовиться ",
  "вовремя",
  "забота, заботиться",
  "наслаждаться, обожать",
  "ненавидеть ",
  "в осовном, по большей части ",
  "отказаться ",
  "точка зрения",
  "вид, взгляд",
  "отношение",
  "выражать ",
  "группа, музыкальная группа",
  "выпускать ",
  "альбом",
  "танец, танцевать ",
  "професионально ",
  "професиональный",
  "чистый",
  "повторить ",
  "ответ, отвечать",
  "доставлять",
  "доставка",
  "посылка",
  "план",
  "улыбка, улыбаться ",
  "навыки аудирования ",
  "очень сильно ",
  "практика, упражнения ",
  "навык, умения ",
  "благодаря ..(чему?)",
  "плакать ",
  "путешествовать ",
  "предпочитать ",
  "улучшать ",
  "личный, личная",
  "каждый из",
  "остров ",
  "жаловаться ",
  "полностью",
  "речь",
  "мотивировать ",
  "приглашать ",
  "обсуждать ",
  "несколько ",
  "публиковать ",
  "писатель ",
  "автор ",
  "мыть , стирать ",
  "блюдо, тарелка",
  "посуда, тарелки ",
  "принадлежать ",
  "прыгать ",
  "желание ",
  "удача",
  "неудача",
  "всего наилучшего ",
  "контролировать, контроль ",
  "готовить ",
  "смеяться",
  "записыват, запись  ",
  "целовать , поцелуй ",
  "провалил, неудача",
  "исправлять, правильный ",
  "разрушать ",
  "заканчивать, финишировать",
  "учиться",
  "совет",
  "советовать ",
  "солдат",
  "торт",
  "уведомление",
  "сразу, немедлино ",
  "шанс",
  "свобода",
  "права",
  "независимость ",
  "звонок",
  "возможность ",
  "рано",
  "сумма",
  "выбрасывать ",
  "последняя модель",
  "равный",
  "часть ",
  "колено ",
  "осторожно ",
  "осторожный",
  "прилечь",
  "преступник",
  "спортсмен",
  "золотая медаль ",
  "переплыть ",
  "через, сквозь",
  "за год ",
  "много времени (*2)",
  "раньше, чем обычно ",
  "позже, чем обычно ",
  "по радио ",
  "где-то",
  "оптимстичный",
  "прекрасно, совершенно ",
  "кредитная карта",
  "к нашему удивлению",
  "уверенный ",
  "уверенно ",
  "музыкант ",
  "городок, город ",
  "разум, ум",
  "сикрет ",
  "обещать, обещание",
  "совсем, вообщем, вовсе",
  "пытался",
  "бесполезный ",
  "гостеприимный",
  "внимание",
  "прибыльный",
  "пример",
  "летом",
  "хорошо оплачиваемая",
  "боль ",
  "инструктор",
  "прямо сейчас",
  "упражнение",
  "в данный момент ",
  "много зарабатывать ",
  "в эти дни ",
  "усердно учится",
  "беднее",
  "на этой недели ",
  "стучать ",
  "стучать в дверь ",
  "говорить по телефону",
  "дождь, идет дождь",
  "снег, идет снег ",
  "зарабатывать ",
  "все лучше и лучше ",
  "на стадионе",
  "в саду",
  "гитара",
  "пианино",
  "не так часто",
  "так часто",
  "тип, печатать ",
  "никогда ",
  "замечать",
  "такого рода",
  "обращать внимание ",
  "три раза в неделю",
  "дважды в неделю",
  "редко (х2)",
  "словарь",
  "в понедельник",
  "по понедельникам",
  "ежедневно ",
  "на выходные",
  "приложение",
  "больше и больше",
  "более популярнее",
  "все еще ",
  "милая, милый",
  "расматривать, учитывать",
  "поиск, искать (х2)",
  "вызывать, звать ",
  "доступный",
  "знания",
  "важность этой вещи",
  "чрезвычайно ",
  "иметь в виду",
  "перед",
  "рядом с ",
  "в",
  "на ",
  "позади ",
  "над",
  "под",
  "между",
  "успех",
  "доступ",
  "входящие",
  "исходящие",
  "испуганный",
  "испытивающий жажду ",
  "застенчивый",
  "выше",
  "ниже",
  "лестница",
  "вниз по лестнице",
  "верх по лестнице",
  "слабый",
  "целое, целый",
  "в общем",
  "половина",
  "сухой ",
  "мокрый",
  "грязный",
  "голова",
  "лоб",
  "щека",
  "подбородок",
  "лицо ",
  "дядя",
  "рука кисть ",
  "ухо",
  "глаз",
  "бровь ",
  "ресницы",
  "нос ",
  "ноздри ",
  "рот ",
  "мышка",
  "губы",
  "зубы",
  "зуб",
  "плечо",
  "грудь",
  "рука полностью",
  "локоть",
  "талия ",
  "живот",
  "бедро возле попы",
  "нога, ножка",
  "бедро в ногах",
  "большой пелец",
  "палец",
  "голень ",
  "лодыжка",
  "палец ноги ",
  "ступня",
  "сиськи",
  "шея",
  "сидеть дома, оставться дома",
  "смотреть на ",
  "растроенный",
  "чайник",
  "кипеть, кипетить",
  "сконцентрироваться ",
  "подождать немного ",
  "повторять, пересматривать (..конспект)",
  "идти на концерт ",
  "для начала ",
  "стоит так дорго ",
  "стоит так дешево",
  "подождать чуть-чуть",
  "ресторан",
  "до скорой встречи",
  "иностранный язык",
  "евро ",
  "когда-нибудь ",
  "еще нет ",
  "англоязычная страна",
  "только, просто",
  "уже",
  "много раз",
  "так много раз",
  "несколько раз",
  "еще",
  "во время, в течении",
  "меры",
  "принимать меры",
  "надлежащие , правильно ",
  "принять надлежащие меры",
  "психология",
  "удилять, посвящать",
  "голосовать , голос",
  "добиться успеха, преуспевать ",
  "если честно ",
  "честный",
  "собираюсь",
  "тысячи раз",
  "около года назад",
  "Ты когда-либо был ...?",
  "упомянуть, упоминание",
  "как я знаю",
  "Я всгеда хотел ....",
  "Я никогда не делал это .",
  "Я никогда не был там .",
  "подходящий",
  "шум",
  "заснуть ",
  "нервничать, занервничать ",
  "пока / в то время как",
  "результаты эказамена",
  "обьевление (то что слышем)",
  "обьевление (в газете, релама)",
  "вчера весь день ",
  "светить ",
  "яркий",
  "ярко ",
  "птица",
  "проснуться",
  "нетерпение",
  "сказать правду, . . .",
  "замок",
  "терпение",
  "захватывающий",
  "в 3 часа дня ",
  "сюжет",
  "интерес",
  "заинтересован в",
  "больше(более) интересоваться",
  "проблема, вопрос",
  "станция, вокзал",
  "гораздо, более",
  "начался сильный дождь",
  "отмена",
  "неприятный",
  "приятный",
  "выходить из-под контроля",
  "рубашка",
  "футболка",
  "блузка",
  "костюм",
  "униформа",
  "платье",
  "юбка",
  "брюки, штаны",
  "джинсы",
  "куртка",
  "плащ, дождевик",
  "пальто",
  "носки",
  "шорты",
  "галстук",
  "пижама",
  "джемпер",
  "свитер",
  "бюстгалтер ",
  "трусики",
  "банный халат ",
  "ванна",
  "колготки",
  "легинсы",
  "носить (одежду)",
  "одеть (одежду)",
  "снять (одежду)",
  "шарф",
  "шапка",
  "кепка",
  "перчатки",
  "ремень, пояс",
  "портфель ",
  "рюкзак(US)",
  "рюкзак(UK)",
  "пакет ",
  "высокий каблук",
  "сандали",
  "кроссовки(US)",
  "кроссовки(UК)",
  "сапоги ",
  "домашний тапочки",
  "шлепанцы",
  "к тому времени",
  "достигать(среднего уровня) ",
  "средний уровень ",
  "провалить тест ",
  "провалить экзамен ",
  "никто",
  "обманывать ",
  "выяснять, обнаруживать ",
  "сказали мне ложь",
  "к трем часам",
  "взлетать ",
  "приземляться, земля ",
  "самолет ",
  "значительно, существенно",
  "значительно, существенно",
  "выглядить как",
  "рай",
  "спорить ",
  "до, раньше, перед",
  "неопределенный, неуверенный",
  "определенный, уверенный",
  "собираюсь сделать ",
  "в ближайшем будущем",
  "оправдать мои ожидании",
  "выступления, производительность ",
  "ничего подобного ",
  "в первый раз",
  "в шоке, шокирован",
  "шок",
  "серьезность ",
  "значимое",
  "подписывать, знак",
  "инициатива",
  "огромный",
  "громадный, огромный",
  "входить, вводить ",
  "очень престижный вуз",
  "плохо, сильно ",
  "повреждать ",
  "остановливаться, прекращать ",
  "сомневаться",
  "долг",
  "отчет",
  "включать ",
  "испытивать, опыт ",
  "повышать ",
  "вероятно ",
  "критиковать ",
  "причина ",
  "без всякой причины",
  "догадывать, угадывать, предпологать",
  "не хватает, недостаток, отсутствие ",
  "дело практики ",
  "покрасить, краска",
  "забор",
  "с помощью",
  "атаковать, атака",
  "враг",
  "удивительный",
  "ошибаться, неправильный",
  "ценить ",
  "трудно поверить ",
  "ничего ",
  "по ошибке",
  "держать ",
  "на руках, на его руках",
  "наказывать, ругать ",
  "вырости (про человека)",
  "постраюсь сделать все возможное",
  "изо всех сил стараться ",
  "исчезать, пропадать ",
  "появляться",
  "осознавать ",
  "прикрепить ",
  "получать (уведомление)",
  "сравнивать ",
  "альтернатива ",
  "в конце дня",
  "обнаруживать ",
  "темнее",
  "разделить на",
  "тест, тестировать ",
  "оканчивать (заведения)",
  "не согласен",
  "соглашаться",
  "заявление, утверждения",
  "самая важная вещь",
  "общаться",
  "откровенный",
  "откровенно говоря",
  "условия, состояние",
  "вести себя, поступать ",
  "возращаться",
  "нажимать ",
  "позитивные эмоции",
  "аудитория",
  "пологаться",
  "странный",
  "незнакомец",
  "расчитывать на, считать ",
  "мечта",
  "изменять, изменения ",
  "обмен, обмениваться",
  "отвечать, ответ ",
  "пнуть, пинать",
  "бить ",
  "слева",
  "справа",
  "уважать ",
  "прерывать ",
  "вообразить, представить ",
  "без этого ",
  "гарантровать ",
  "опасность ",
  "изымать, снимать, отзывать ",
  "счет",
  "должен работать над",
  "должен",
  "вести, приводить ",
  "приводить к",
  "мог бы",
  "(присматривать, следить) за",
  "должен, следует ",
  "возможно, может (*3)",
  "может быть ",
  "бы",
  "привлекать ",
  "друг друга",
  "сообщить ",
  "сообщить об",
  "отдалживать",
  "подметать пол",
  "подметать",
  "подтверждать",
  "кататься на лошади",
  "кататься на велосипеде ",
  "жениться",
  "жениться на ней",
  "замуж за него",
  "как можно скорее",
  "многочисленные",
  "управлять, суметь",
  "суметь сделать что-то",
  "преодолеть ",
  "одобряю",
  "щетка, чистить",
  "установливать ",
  "уменьшать, снижать",
  "жаловаться на это ",
  "класть, ложить",
  "брать ",
  "занять первое место ",
  "невороятно",
  "инвестировать, вкладывать деньги",
  "реагировать на",
  "реагировать",
  "предлогать",
  "сегодня вечером",
  "соответсвовать, подходить",
  "ремонтировать, ремонт",
  "восхищаться",
  "доверять",
  "трогать, косаться",
  "скучать, пропускать",
  "занимать (пример: деньги)",
  "нести",
  "наполнять",
  "заполнять",
  "заполнять (пропуски, пробелы)",
  "зазазор, разрыв, пробел",
  "извеняться ",
  "извеняться за",
  "грубый",
  "поведение",
  "копировать ",
  "адаптироваться",
  "адаптироваться к",
  "хотя",
  "слегка",
  "дуть",
  "представлять",
  "разрешите, дайте мне",
  "удовольствие",
  "обожать",
  "изобретать",
  "ученый",
  "екстроординарный, необычный",
  "на регулярной основе",
  "основа",
  "копать",
  "дыра, яма, отверстия",
  "в земле",
  "бриться",
  "борода",
  "портиться, портить",
  "торопится",
  "всех нас",
  "курить",
  "взять на прокат, орендовать",
  "запрещать",
  "над ним",
  "унизительный",
  "унижать",
  "анлизировать",
  "тщательно",
  "как я понимаю",
  "насколько я понимаю",
  "как можно больше",
  "арестовывать",
  "давайте",
  "подписываться",
  "должен(not modail Verb)",
  "отрицать(x2)",
  "из-за",
  "должен/придеться (not modail Verb)",
  "уставать",
  "растроенный",
  "опаздывать",
  "вот почему, поэтому",
  "вероятно, возможно",
  "срочный",
  "офицальная встреча",
  "оставаться",
  "хвалить",
  "худше",
  "худший",
  "плохой",
  "червяк",
  "источник",
  "трогательный",
  "ответственный",
  "сотрудник",
  "работадатель",
  "распростроненный, общий",
  "среди",
  "это одно из...",
];

const col_2 = [
  "support",
  "lake",
  "river",
  "advice",
  "famous",
  "table",
  "desk",
  "sit down",
  "stand up ",
  "fast",
  "run away ",
  "break down ",
  "bridge",
  "at first ",
  "really",
  "bring",
  "real",
  "happiness",
  "enaugh",
  "correctly ",
  "solve",
  "pass",
  "exam",
  "excursion",
  "trip",
  "homework",
  "celebrate",
  "holiday",
  "absolutely",
  "sad",
  "me",
  "you",
  "him",
  "her",
  "it",
  "us",
  "our",
  "your",
  "them",
  "their",
  "this",
  "these",
  "that",
  "those",
  "tired",
  "ill",
  "angry",
  "unusually",
  "surprised",
  "joke",
  "download",
  "effective",
  "minute",
  "muscles",
  "half an hour",
  "clothes",
  "virus",
  "matter",
  "inspire",
  "exist ",
  "such",
  "theory",
  "can ",
  "everything ",
  "not everything",
  "depend",
  "method",
  "also",
  "opinion",
  "same",
  "person ",
  "sound",
  "attractive",
  "world",
  "quite",
  "enjoy English ",
  "because",
  "great",
  "native speaker",
  "wonderful",
  "inspiration",
  "true",
  "clear",
  "task ",
  "excellent",
  "brilliant ",
  "building",
  "high",
  "low",
  "feeling",
  "tasty ",
  "nowadays",
  "children",
  "child",
  "kids",
  "kid",
  "weather",
  "smart",
  "clever",
  "talanted",
  "look",
  "looks",
  "strong",
  "the same",
  "parents ",
  "cousin ",
  "expression ",
  "effective",
  "cold",
  "warm ",
  "hot",
  "sunny",
  "windy",
  "wind",
  "necessary",
  "detail",
  "detailed",
  "informative",
  "description ",
  "describe",
  "surprise",
  "motivation",
  "motivates",
  "motivate",
  "simple",
  "a sales manager",
  "a shop assistant",
  "lawyer",
  "law",
  "recommend",
  "souvenir",
  "translate",
  "worry",
  "foreign",
  "language",
  "as for me",
  "expect",
  "one day",
  "sooner or later ",
  "suppose",
  "save up ",
  "hope",
  "afraid",
  "misunderstand",
  "reliable",
  "one more time",
  "screen",
  "from time to time",
  "foreigner",
  "at the exhibition ",
  "almost ",
  "a consultant",
  "call me back",
  "achieve",
  "couple",
  "something",
  "wise",
  "training",
  "dark",
  "turn ",
  "explanation ",
  "unexpectedly",
  "follow",
  "recommendation ",
  "explain",
  "waste",
  "create",
  "difficulties",
  "then",
  "remember",
  "a bit",
  "die",
  "income",
  "kill",
  "successful",
  "successfully",
  "success",
  "ability",
  "develop",
  "thank",
  "goods",
  "produce",
  "factory",
  "product",
  "trouble",
  "in trouble",
  "always",
  "join",
  "close",
  "share",
  "link",
  "save ",
  "prepare",
  "on time",
  "care",
  "enjoy",
  "hate",
  "mostly",
  "refuse",
  "point of view",
  "view",
  "attitude",
  "express",
  "band",
  "release",
  "album ",
  "dance",
  "professional",
  "professionally",
  "clean",
  "repeat ",
  "answer",
  "deliver",
  "delivery",
  "parcel",
  "plan",
  "smile",
  "listening skills",
  "greatly",
  "practice",
  "skill",
  "thank to ",
  "cry",
  "travel",
  "prefer",
  "improve",
  "personal",
  "each of",
  "island",
  "complain ",
  "completely",
  "speech",
  "motivate",
  "invite",
  "discuss",
  "several",
  "publish",
  "writer",
  "author",
  "wash",
  "dish",
  "dishes",
  "belong to",
  "jump",
  "wish",
  "good luck",
  "bad luck",
  "all the best",
  "control",
  "cook",
  "laugh",
  "record",
  "kiss",
  "fail",
  "correct ",
  "destroy",
  "finish",
  "study",
  "advice",
  "advise",
  "soldier",
  "cake",
  "notification",
  "immediately",
  "chance",
  "freedom",
  "rights",
  "independence",
  "bell",
  "opportunity",
  "early",
  "sum",
  "throw away",
  "the latest model",
  "equal",
  "part",
  "knee",
  "carefully",
  "careful",
  "lie down",
  "criminal",
  "sportsman",
  "the gold medal",
  "swim across",
  "across",
  "in a year",
  "a lot of time, lots of time",
  "eaerlier than usual",
  "later than usual",
  "on the radio",
  "somewhere",
  "optimistic",
  "perfectly",
  "credit card",
  "to our surprise",
  "confident",
  "confidently",
  "musician",
  "town",
  "mind",
  "sicret",
  "promise",
  "at all",
  "tried",
  "useless",
  "hospitable",
  "attention ",
  "profitable",
  "example",
  "in summer",
  "well-paid",
  "pain",
  "instructor",
  "right now",
  "exercises",
  "at the moment ",
  "earn a lot",
  "these days",
  "study a hard",
  "pooer",
  "this week",
  "knock",
  "knock at the door",
  "talk on the phone",
  "rain ",
  "snow",
  "earn",
  "better and better",
  "at the stadium ",
  "in the garden ",
  "the guitar",
  "the piano",
  "not so often",
  "so often",
  "type",
  "never",
  "notice",
  "this kind of",
  "pay attention ",
  "three times a week",
  "twice a week",
  "seldom, rarely",
  "dictionary",
  "on Monday",
  "on Mondays",
  "daily",
  "at the weekend",
  "application ",
  "biger and biger",
  "more popular",
  "still",
  "cute",
  "consider",
  "search, look for",
  "call",
  "available",
  "knowledge",
  "the importance of this thing",
  "extremely",
  "mean",
  "in front of",
  "next to ",
  "in ",
  "on",
  "behind",
  "over",
  "under",
  "between",
  "success",
  "access",
  "inbox",
  "outbox",
  "scared",
  "thirsty",
  "shy",
  "above",
  "below",
  "stairs",
  "downstairs",
  "upstairs",
  "weak",
  "whole",
  "on the whole",
  "half",
  "dry",
  "wet",
  "dirty",
  "hed",
  "forehead",
  "cheek",
  "chin",
  "face",
  "uncle",
  "hand",
  "ear",
  "eye",
  "eyebrow",
  "eyelashes",
  "nose",
  "nostrils",
  "mouth",
  "mouse",
  "lips",
  "teeth",
  "tooth",
  "shoulder",
  "chest",
  "arm",
  "elbow",
  "waist",
  "stomach",
  "hip",
  "leg",
  "thigh",
  "thumb",
  "finger",
  "shin",
  "ankle",
  "toe",
  "foot",
  "tits, boobs",
  "neck",
  "stay at home",
  "look at",
  "upset",
  "kettl",
  "boil",
  "concentrate",
  "wait a little",
  "revise",
  "go to the concert",
  "for a start",
  "cost so much",
  "cost a little",
  "wait a bit",
  "restaurant",
  "see you soon",
  "foreign language",
  "euro",
  "ever",
  "not yet",
  "an English-speaking country",
  "just",
  "already",
  "many times",
  "so many times",
  "several times",
  "yet",
  "during",
  "measures",
  "take measures",
  "proper",
  "take proper measures",
  "psychology",
  "devote to",
  "vote",
  "succeed",
  "to be honest",
  "honest",
  "going to",
  "a thousand times",
  "about a year ago",
  "Have you ever been to …?",
  "mention",
  "as I know",
  "I`ve always wanted to ….",
  "I`ve never done it .",
  "I`ve never been there .",
  "suitable",
  "noise",
  "fall asleep",
  "get nervous",
  "while",
  "the exam results",
  "announcement",
  "advertisement",
  "all day yesterday",
  "shine",
  "bright",
  "brightly",
  "bird",
  "wake up",
  "impatience",
  "to tell the truth, . . .",
  "castle",
  "patience",
  "thrilling",
  "at 3 o`clock in the afternoon",
  "plot",
  "interest",
  "interested in ",
  "get more interested in ",
  "issue",
  "station",
  "much more",
  "it started raining heavily",
  "cancel",
  "unpleasant",
  "pleasant",
  "get out of control",
  "shirt",
  "t-shirt",
  "blouse",
  "suit",
  "uniform ",
  "dress",
  "skirt",
  "trousers",
  "jeans",
  "jacket",
  "raincoat",
  "coat",
  "socks",
  "shorts",
  "tie",
  "pyjamas",
  "jumper",
  "sweater",
  "bra",
  "panties",
  "bathrobe",
  "bath",
  "tights",
  "leggings",
  "to wear ",
  "to put on ",
  "to take off",
  "scharf",
  "hat ",
  "cap",
  "gloves",
  "belt",
  "briefcase",
  "backpack",
  "rucksack",
  "pack",
  "high heels",
  "sandals",
  "sneakers",
  "trainers",
  "boots",
  "slippers",
  "flips-flops",
  "by the time",
  "reach",
  "an intermediate level",
  "fail the test",
  "fail the exam",
  "no one ",
  "deceive",
  "find out",
  "told me a lie",
  "by three o`clock",
  "take off",
  "land",
  "plane",
  "significantly",
  "considerably",
  "look like ",
  "paradise",
  "argue",
  "before",
  "uncertain ",
  "certain ",
  "to be going to do",
  "in the near future",
  "live up to my expectations",
  "performance",
  "anything like it",
  "for the first time",
  "shocked",
  "shock",
  "seriousness",
  "meaningful",
  "sign",
  "initiative",
  "huge",
  "tremendous",
  "enter",
  "a very prestigious university",
  "badly",
  "damage",
  "stop",
  "doubt",
  "debt",
  "report",
  "include",
  "experience",
  "increase",
  "probably",
  "criticize",
  "reason",
  "for no reason",
  "guess",
  "lack",
  "a matter of practice",
  "paint",
  "fence",
  "with the help of",
  "attack",
  "enemy",
  "amazing",
  "wrong",
  "appreciate",
  "it is hard to believe",
  "nothing",
  "by mistake",
  "hold",
  "in his arms",
  "punish",
  "grow up ",
  "try to do my best",
  "try to do my best",
  "disappear",
  "appear",
  "realize",
  "attach to",
  "receive",
  "compare",
  "alternative",
  "at the end of the day",
  "discover",
  "darker",
  "divide into",
  "test",
  "graduate from",
  "disagree",
  "agree",
  "statement",
  "the most important thing",
  "communicate",
  "frank",
  "to be frank",
  "condition ",
  "behave",
  "return",
  "press",
  "positive emotions",
  "audience",
  "rely on",
  "strange",
  "stranger",
  "count on ",
  "dream",
  "change",
  "exchange",
  "reply to",
  "kick",
  "beat",
  "on the left",
  "on the right",
  "respect",
  "interrupt",
  "imagine",
  "without it",
  "guarantee",
  "danger",
  "withdraw",
  "account",
  "must work on",
  "must",
  "lead",
  "lead to ",
  "could",
  "look after",
  "should",
  "may, probably, might",
  "maybe",
  "would",
  "attract",
  "each other",
  "inform",
  "inform of",
  "lend",
  "sweep the floor",
  "sweep",
  "confirm",
  "ride a hourse",
  "ride a bike",
  "marry",
  "marry her",
  "marry him",
  "as soon as possible",
  "numerous",
  "manage",
  "manage to do something",
  "overcome",
  "approve of",
  "brush",
  "set up",
  "decrease",
  "complain about it",
  "lay",
  "take",
  "take the first place",
  "incredibly",
  "invest",
  "react to",
  "react",
  "suggest",
  "tonight",
  "fit",
  "repair",
  "admire",
  "trust",
  "touch",
  "miss",
  "borrow",
  "carry",
  "fill",
  "fill in",
  "fill in the gaps",
  "gap",
  "apologize",
  "apologize for",
  "rude",
  "behaviour",
  "copy",
  "adapt",
  "adapt to",
  "although",
  "slightly",
  "blow",
  "introduce",
  "let me",
  "pleasure",
  "adore",
  "invent",
  "scientist",
  "extraordinary",
  "on a regular basis",
  "basis",
  "dig",
  "hole",
  "in the ground",
  "shave",
  "beard",
  "spoil",
  "hurry up",
  "all of us",
  "smoke",
  "rent",
  "forbid",
  "at him",
  "humiliating",
  "humiliate",
  "analyze",
  "thoroughly",
  "as I understand",
  "as for as I understand",
  "as much as possible",
  "arrest",
  "let's",
  "subsrcibe to",
  "ought to ",
  "deny, negate",
  "because of",
  "have to",
  "get tired",
  "disappointed",
  "to be late",
  "that's why",
  "perhaps",
  "urgent",
  "appointment",
  "remain",
  "praise",
  "worse",
  "the worst",
  "bad",
  "worm",
  "source",
  "moving",
  "responsible",
  "employee",
  "employer",
  "common",
  "among",
  "it's one of",
];

const uniqueArrWords = [];
for (let i = 0; i < col_1.length; i++) {
  uniqueArrWords.push({ id: i + 1, colOne: col_1[i], colTwo: col_2[i] });
}

class App extends React.Component {
  state = {
    modeDark: false,
    textareaOne: "",
    textareaTwo: "",
    arreysWord: [],
    duplicArreysWord: [],
    arrayWin: [],
    arrayLose: [],
    err: false,
    success: false,
    indexRandom: 0,

    inputWord: "",
    inputWordDuplicat: "",
    checkWin: false,
    checkLose: false,
    help: false,
  };

  changeTextAreaOne = (e) => {
    this.setState(() => {
      return {
        textareaOne: e.target.value,
      };
    });
  };

  changeTextAreaTwo = (e) => {
    this.setState(() => {
      return {
        textareaTwo: e.target.value,
      };
    });
  };

  cleanTextareaOne = () => {
    this.setState(() => {
      return {
        textareaOne: "",
        arreysWord: [],
      };
    });
  };

  cleanTextareaTwo = () => {
    this.setState(() => {
      return {
        textareaTwo: "",
        arreysWord: [],
      };
    });
  };

  toggleModeState = () => {
    this.setState(({ modeDark }) => {
      return {
        modeDark: !modeDark,
      };
    });
  };

  reverseArray = async () => {
    const strCol_1 = this.state.textareaOne;
    const strCol_2 = this.state.textareaTwo;

    await this.setState(() => {
      return {
        textareaOne: strCol_2,
        textareaTwo: strCol_1,
      };
    });

    await this.addedWordsInArray();
  };

  addedWordsInArray = async () => {
    const arrayOne = this.state.textareaOne.split("\n");
    const arrayTwo = this.state.textareaTwo.split("\n");

    const arrNew = [];

    for (let i = 0; i < arrayOne.length; i++) {
      arrNew.push({ id: i + 1, colOne: arrayOne[i], colTwo: arrayTwo[i] });
    }

    if (arrayOne[0] === "" || arrayTwo[0] === "0") {
      console.log("+");
    } else {
      await this.setState(() => {
        return {
          arreysWord: arrNew,
        };
      });
    }

    // check for success
    if (this.state.arreysWord.length > 1) {
      await this.setState(() => {
        return {
          success: true,
        };
      });
      await setTimeout(() => this.setState({ success: false }), 3000);
    }
  };

  uniqueWords = () => {
    const textareaOneNew = col_1.join().replace(/\,/g, "\n");
    const textareaTwoNew = col_2.join().replace(/\,/g, "\n");

    console.log(textareaOneNew);
    this.setState(() => {
      return {
        arreysWord: [...uniqueArrWords],
        textareaOne: textareaOneNew,
        textareaTwo: textareaTwoNew,
      };
    });
  };

  checkForEmptiness = () => {
    if (this.state.arreysWord.length === 0) {
      this.setState(() => {
        return {
          err: true,
        };
      });

      setTimeout(() => {
        this.setState({ err: false });
      }, 3000);
    }
  };

  showRandomWord = () => {
    const { arrayWin, duplicArreysWord } = this.state;

    const duplicWordCount = duplicArreysWord.length; // [{},{},{}]
    const newRanomIndex = Math.floor(Math.random() * (duplicWordCount - 1)); // random: 0,1,2... (1)

    if (arrayWin.length !== 0) {
      this.setState(() => {
        return {
          indexRandom: newRanomIndex,
        };
      });
    }
  };

  handleWordChange = (event) => {
    this.setState({ inputWord: event.target.value });

    // if pressed on keyboard 'enter'
    if (event.keyCode === 13) {
      this.checkForMatches();
    }

    // if pressed on keyboard 'ctrl'
    if (event.keyCode === 17) {
      this.showHelp();
    }
  };

  checkForMatches = () => {
    const { arrayWin, arrayLose, indexRandom, inputWord, duplicArreysWord } =
      this.state;

    const duplicWordCount = duplicArreysWord.length; // word count

    const word = duplicArreysWord[indexRandom].colTwo.toLowerCase().trim(); // colon_1 CheckPage.jsx
    const wordInput = inputWord.toLowerCase().trim(); // colon_2 INPUT CheckPage.jsx
    console.log(wordInput);

    const objCurrent = duplicArreysWord[indexRandom]; // current object

    //_______________________________________check LOSE

    if (word !== wordInput) {
      this.setState(() => {
        return {
          checkLose: true,
          checkWin: false,
          inputWord: "",
          inputWordDuplicat: wordInput,
        };
      });

      setTimeout(
        () => this.setState({ checkLose: false, checkWin: false }),
        3000
      );

      if (!arrayLose.includes(objCurrent)) {
        const newArreysWord = duplicArreysWord.filter(
          (item) => item !== objCurrent
        );

        this.setState(({ arrayLose }) => {
          return {
            arrayLose: [...arrayLose, objCurrent],
            duplicArreysWord: newArreysWord,
          };
        });
      }
    }

    //_______________________________________check WIN!!!

    if (word === wordInput) {
      this.setState(() => {
        return {
          checkWin: true,
          checkLose: false,
          inputWord: "",
        };
      });

      setTimeout(
        () => this.setState({ checkLose: false, checkWin: false }),
        3000
      );

      if (!arrayWin.includes(objCurrent)) {
        const newArreysWord = duplicArreysWord.filter(
          (item) => item !== objCurrent
        );

        this.setState(({ arrayWin }) => {
          return {
            arrayWin: [...arrayWin, objCurrent],
            duplicArreysWord: newArreysWord,
          };
        });
        this.showRandomWord();
      }

      // if (duplicWordCount === 0) {
      //   this.setState(({ arrayWin }) => {
      //     return {
      //       arrayWin: [...arrayWin, objCurrent],
      //       duplicArreysWord: [{ colOne: "win", colTwo: "win" }],
      //     };
      //   });
      // } else if (!arrayWin.includes(objCurrent)) {
      //   const newArreysWord = duplicArreysWord.filter(
      //     (item) => item !== objCurrent
      //   );

      //   this.setState(({ arrayWin }) => {
      //     return {
      //       arrayWin: [...arrayWin, objCurrent],
      //       duplicArreysWord: newArreysWord,
      //     };
      //   });
      //   // await this.showRandomWord();
      // }
    }
  };

  btnGame = () => {
    this.setState(({ arreysWord }) => {
      return {
        arrayLose: [],
        arrayWin: [],
        duplicArreysWord: arreysWord,
      };
    });
  };

  showHelp = () => {
    this.setState(() => {
      return {
        help: true,
      };
    });

    setTimeout(() => this.setState({ help: false }), 4000);
  };

  componentDidMount() {
    // this.showRandomWord();
  }

  componentDidUpdate(prevProps, prevState) {}

  render() {
    const {
      modeDark,
      textareaOne,
      textareaTwo,
      arreysWord,
      err,
      success,
      indexRandom,
      inputWord,
      inputWordDuplicat,
      arrayWin,
      arrayLose,
      duplicArreysWord,
      checkLose,
      checkWin,
      help,
      showError,
    } = this.state;

    const styleMode = modeDark ? "app" : "app dark_mode";

    return (
      <div className={styleMode}>
        <Routes>
          <Route
            path="/"
            element={
              <Layout
                toggleModeState={this.toggleModeState}
                modeDark={modeDark}
              />
            }
          >
            <Route index element={<InfoPage modeDark={modeDark} />} />
            <Route
              path="main"
              element={
                <MainPages
                  modeDark={modeDark}
                  textareaOne={textareaOne}
                  textareaTwo={textareaTwo}
                  changeTextAreaOne={this.changeTextAreaOne}
                  changeTextAreaTwo={this.changeTextAreaTwo}
                  cleanTextareaOne={this.cleanTextareaOne}
                  cleanTextareaTwo={this.cleanTextareaTwo}
                  addedWordsInArray={this.addedWordsInArray}
                  reverseArray={this.reverseArray}
                  arreysWord={arreysWord}
                  checkForEmptiness={this.checkForEmptiness}
                  err={err}
                  success={success}
                  uniqueWords={this.uniqueWords}
                />
              }
            />
            <Route
              path="check"
              element={
                <CheckPage
                  modeDark={modeDark}
                  arreysWord={arreysWord}
                  btnGame={this.btnGame}
                />
              }
            />
            <Route
              path="game"
              element={
                <GamePage
                  modeDark={modeDark}
                  arreysWord={arreysWord}
                  indexRandom={indexRandom}
                  handleWordChange={this.handleWordChange}
                  inputWord={inputWord}
                  inputWordDuplicat={inputWordDuplicat}
                  checkForMatches={this.checkForMatches}
                  duplicArreysWord={duplicArreysWord}
                  arrayWin={arrayWin}
                  arrayLose={arrayLose}
                  checkLose={checkLose}
                  checkWin={checkWin}
                  showHelp={this.showHelp}
                  help={help}
                />
              }
            />
            <Route path="*" element={<NotfoundPage />} />
          </Route>
        </Routes>
      </div>
    );
  }
}

export default App;
